Update use of termios object
The following commit changed the api:

  commit adc8d746caa67fff4b53ba3e5163a6cbacc3b523
  Author: Alan Cox <alan@linux.intel.com>
  Date:   Sat Jul 14 15:31:47 2012 +0100

      tty: move the termios object into the tty

This fixes the following build failure against 3.13:

  xr21v141x-lnx-3.5-pak/vizzini.c: In function ‘xr21v141x_tty_set_termios’:
  xr21v141x-lnx-3.5-pak/vizzini.c:1096:22:
  error: invalid type argument of ‘->’ (have ‘struct ktermios’)
    cflag = tty->termios->c_cflag;

Signed-off-by: Joel Stanley <joel@jms.id.au>